### ISSUE TITLE
 "Click tags order" from settings does not order the tags created.

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#652] opened 2021-07-12 22:02 UTC
1. In Taxonomy -> Settings -> Administration -> Click tags order -> name-desc and update
2. Select Tags and check the order

Tags order should be displayed in descending order. Tags are displayed in default order asc.

Select any option other than name-asc and observe the order of the tags. Tags are always displayed in asc order.

![tags order](https://user-images.githubusercontent.com/83974581/125361401-1a072080-e322-11eb-96f5-f7dd0d0be1f8.JPG)
![tags](https://user-images.githubusercontent.com/83974581/125361406-1a9fb700-e322-11eb-9cf2-39a06985e5e1.JPG)

**Comment by olatechpro** [comment] 2021-07-13 08:00
@stevejburge and @sathyapriya91 , i can't see the page you are in the second screenshot as the menu part is cut off but for clarity, click tags is not taxonomy and the settings applies to post edit/create page as shown in the screenshot below and not taxonomy page. So, closing this issue as it's working as intended on the right page.

<img width="1440" alt="Screenshot 2021-07-13 at 8 58 31 AM" src="https://user-images.githubusercontent.com/46832636/125414417-fa88cca6-6e06-40b7-85fd-4ccc34b5689d.png">

**Closed by olatechpro** 2021-07-13 08:00 UTC
