### ISSUE TITLE
Move metabox API keys and settings directly into Auto Terms

### ISSUE THREAD

**Issue by stevejburge** [TaxoPress/TaxoPress#2106] opened 2024-08-07 17:15 UTC
Can we manage the API keys directly inside Auto Terms?

![Screenshot 2024-08-07 at 1 14 44 PM](https://github.com/user-attachments/assets/018c8016-38da-4874-aa34-dde6bd137170)

**Comment by ojopaul** [comment] 2024-09-09 14:58
@stevejburge You can not manage the API Keys here but it's possible to have API keys fields inside the Auto Terms too but that shows it'll be duplicate of what we have in metabox settings and whatever changes you made in any Auto Term settings does not automatically get updated in metabox settings and vice versa

**Comment by stevejburge** [comment] 2024-09-09 15:09
Thanks @ojopaul. That's good enough for now. 

Slowly, I'd like us to move towards having all important settings inside "Auto Terms'

**Comment by ojopaul** [comment] 2024-09-13 05:39
I think the API key can be removed from metabox settings after implementing this second part https://github.com/TaxoPress/TaxoPress/issues/2101

**Closed** 2024-09-18 10:36 UTC
