### ISSUE TITLE
Post is not auto tagged when 'Autotag only Posts without terms' target is selected 

### ISSUE THREAD

**Issue by sathyapriya91** [TaxoPress/TaxoPress#611] opened 2021-06-30 16:44 UTC
1. In Auto terms, Posts->Categories, Activate Auto Tags for the Categories taxonomy
2. Add a term in the Keywords list
3. Select the Target -> Autotag only Posts without terms
4. Create a post with that term in it
5. Publish the post and observe the result

The term should be added to the post as it matches the term in the keywords list, but it is not added when 'Autotag only Posts without terms' target is selected. 

![word press](https://user-images.githubusercontent.com/83974581/123999471-68620a00-d987-11eb-9a5b-829dd946f1dc.JPG)
![word press1](https://user-images.githubusercontent.com/83974581/123999475-68faa080-d987-11eb-8d52-b1cd652e4188.JPG)

**Comment by olatechpro** [comment] 2021-09-02 17:51
@stevejburge, can you check if you're able to product this issue ?
Testing here works fine

**Comment by olatechpro** [comment] 2021-09-02 18:07
Update: I think the issue is, auto terms is not working with category in general. 
It seems to work with tags but category in general. So, will be checking why and update.

It covers #600 too

**Comment by olatechpro** [comment] 2021-09-03 09:51
So, based on my further investigation and debugging on this issue, this feature is working as expected except when user check **'Autotag only Posts without terms'** for 'category' which is not true as category is always with term(Uncategorized) even when not selected which is the reason that condition cannot work for category and works for others.

So, should we close this now or you want anything done on this issue @stevejburge  ?

**Comment by stevejburge** [comment] 2021-09-03 13:17
Thanks @olatechpro Yes, let's close for now

**Closed by stevejburge** 2021-09-03 13:17 UTC
Labels: bug
